[workspace]
resolver = "2"
members = [
    "crates/bazof",
    "crates/bazof-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Maciej Lesiczka <maciej.lesiczka@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/MaciekLesiczka/bazof"
